[package]
name = "polymorph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = "0.16.0"
reqwest = "0.12.2"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
